#!/bin/sh
# Needs zenity, notify-send and wget
# This is the directory where the trailer is to be saved
DIR=~/Downloads
url=$(zenity --entry --text="Enter the URL")
if [ $? -eq 0 ]; then
    url=$(echo $url | sed -r "s#(480|720|1080)p#h\1p#")
    filename=$(basename $url)
    wget -U Quicktime/7.6.2 -O $DIR/$filename $url
    if [ $? -eq 0 ]; then
        notify-send "Download complete" "$filename has been downloaded"
        choice=$(zenity --question --title="Download complete" --text="Play $filename ?")
        if [ $? -eq 0 ]; then
            mplayer $DIR/$filename &
        fi
    else
        notify-send "Download failed" "$filename could not be downloaded"
    fi
fi
